//! Numerical parity: hexo-infer's forward pass vs the eager PyTorch oracle,
//! pinned by fixtures generated by `hexo_a0.gen_parity_fixtures`.

use hexo_infer::InferModel;
use hexo_rs::axis_graph::game_to_axis_graph_raw_opts;
use hexo_rs::hexo_engine::{GameConfig, GameState};
use serde::Deserialize;
use std::path::PathBuf;

#[derive(Deserialize)]
struct Fixture {
    name: String,
    game_config: GC,
    graph_opts: GO,
    #[serde(default)]
    checkpoint: Option<String>, // real fixtures only
    moves: Vec<[i32; 2]>,
    expected: Expected,
}
#[derive(Deserialize)]
struct GC {
    win_length: u8,
    placement_radius: i32,
    max_moves: u32,
}
#[derive(Deserialize)]
struct GO {
    prune_empty_edges: bool,
    threat_features: bool,
    relative_stones: bool,
}
#[derive(Deserialize)]
struct Expected {
    value: f64,
    logits: Vec<([i32; 2], f64)>,
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn load_fixture(name: &str) -> Fixture {
    let p = fixtures_dir().join(format!("{name}.json"));
    serde_json::from_str(&std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("{p:?}: {e}")))
        .unwrap_or_else(|e| panic!("{p:?}: {e}"))
}

fn replay(fx: &Fixture) -> GameState {
    let mut game = GameState::with_config(GameConfig {
        win_length: fx.game_config.win_length,
        placement_radius: fx.game_config.placement_radius,
        max_moves: fx.game_config.max_moves,
    });
    for m in &fx.moves {
        game.apply_move((m[0], m[1])).unwrap();
    }
    game
}

fn assert_parity(model: &InferModel, fx: &Fixture, tol: f64) {
    let game = replay(fx);
    let g = game_to_axis_graph_raw_opts(
        &game,
        fx.graph_opts.prune_empty_edges,
        fx.graph_opts.threat_features,
        fx.graph_opts.relative_stones,
    );
    let (logits, value) = model.forward(&g);
    assert_eq!(logits.len(), fx.expected.logits.len(), "{}: legal count", fx.name);
    let legal = game.legal_moves();
    let mut max_dev = 0.0f64;
    for (i, (coord, expected)) in fx.expected.logits.iter().enumerate() {
        assert_eq!(legal[i], (coord[0], coord[1]), "{}: legal order @{i}", fx.name);
        let dev = (logits[i] as f64 - expected).abs();
        max_dev = max_dev.max(dev);
        assert!(
            dev < tol,
            "{}: logit[{i}] {} vs {} (dev {dev:e})",
            fx.name, logits[i], expected
        );
    }
    let vdev = (value as f64 - fx.expected.value).abs();
    max_dev = max_dev.max(vdev);
    assert!(vdev < tol, "{}: value {} vs {} (dev {vdev:e})", fx.name, value, fx.expected.value);
    eprintln!("{}: max abs deviation {max_dev:e}", fx.name);
}

/// Closes the parity suite's ordering blind spot: both fixture generator and Rust
/// forward label logits by legal_moves() order via the same graph builder, so a
/// divergence between graph legal-node order and legal_moves() would pass parity
/// while mislabeling every move. Assert the invariant directly.
#[test]
fn legal_node_order_matches_legal_moves() {
    let mut game = GameState::with_config(GameConfig { win_length: 6, placement_radius: 4, max_moves: 300 });
    for m in [(1, 0), (-1, 0), (0, 1), (0, -1)] {
        game.apply_move(m).unwrap();
    }
    let g = game_to_axis_graph_raw_opts(&game, true, true, true);
    let legal = game.legal_moves();
    let n_stones = g.stone_mask.iter().filter(|&&b| b).count();
    for (j, &c) in legal.iter().enumerate() {
        let idx = n_stones + j;
        assert!(g.legal_mask[idx], "node {idx} must be a legal-move node");
        assert_eq!((g.coords[idx * 2], g.coords[idx * 2 + 1]), c, "legal node {j} order");
    }
}

/// Threaded batch eval (native eval_states with len > 1) must be bitwise
/// identical, in order, to per-state serial evals (len == 1 stays serial).
#[test]
fn threaded_batch_eval_matches_serial() {
    let bytes = std::fs::read(fixtures_dir().join("tiny.safetensors")).unwrap();
    let model = InferModel::from_safetensors(&bytes).unwrap();
    let mut game = GameState::with_config(GameConfig { win_length: 6, placement_radius: 4, max_moves: 300 });
    let mut states = vec![game.clone()];
    for m in [(1, 0), (-1, 0), (0, 1), (0, -1), (2, 0), (1, 1), (0, 2)] {
        game.apply_move(m).unwrap();
        states.push(game.clone());
    }
    let (maps, values) = model.eval_states(&states);
    for (i, st) in states.iter().enumerate() {
        let (m1, v1) = model.eval_one(st);
        assert_eq!(maps[i], m1, "state {i}: logit map mismatch");
        assert_eq!(values[i], v1, "state {i}: value mismatch");
    }
}

#[test]
fn tiny_model_parity() {
    for (weights, prefix) in [("tiny.safetensors", "tiny"), ("tiny_nojk.safetensors", "tiny_nojk")] {
        let bytes = std::fs::read(fixtures_dir().join(weights)).unwrap();
        let model = InferModel::from_safetensors(&bytes).unwrap();
        for pos in ["initial", "early_5", "midturn_9", "mid_20"] {
            let fx = load_fixture(&format!("{prefix}_{pos}"));
            assert_parity(&model, &fx, 1e-4);
        }
    }
}

/// Real-model parity, env-gated on HEXO_REAL_WEIGHTS. If the pin file exists (the
/// real-model chain was set up in this clone), refusing to skip prevents the gate
/// from silently no-oping.
const REAL_PARITY_TOL: f64 = 1e-3; // if loosened per the tolerance rule, record measured max + date here

#[test]
fn real_model_parity() {
    let Ok(path) = std::env::var("HEXO_REAL_WEIGHTS") else {
        let pin = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../exports/PINNED_CHECKPOINT");
        assert!(
            !pin.exists(),
            "exports/PINNED_CHECKPOINT exists but HEXO_REAL_WEIGHTS is unset — refusing to silently skip real parity"
        );
        eprintln!("HEXO_REAL_WEIGHTS unset; skipping real-model parity");
        return;
    };
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("{path}: {e}"));
    let model = InferModel::from_safetensors(&bytes).unwrap();
    for pos in ["initial", "early_5", "midturn_9", "mid_20"] {
        let fx = load_fixture(&format!("real_{pos}"));
        // Consistency gate: fixtures and weights MUST come from the same pinned
        // checkpoint — turns a numeric mismatch into an explicit error.
        assert_eq!(
            fx.checkpoint.as_deref(),
            Some(model.source_checkpoint()),
            "{}: fixture minted from a different checkpoint than the loaded weights",
            fx.name
        );
        assert_parity(&model, &fx, REAL_PARITY_TOL);
    }
}